# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 19:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=b'')),
            ],
        ),
    ]
