# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0002_auto_20160209_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
