# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0006_auto_20160210_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.TextField(default='Javascript'),
            preserve_default=False,
        ),
    ]
