# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0007_project_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/splash/')),
            ],
        ),
    ]
