# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0008_splash'),
    ]

    operations = [
        migrations.AddField(
            model_name='splash',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
